Repository crowbar/crowbar-core, pull requests merged in 2018-10, with the labels that each got.

#1669 [5.0] provisioner: Skip vxlan virtual devices
  chef/cookbooks/ohai/recipes/default.rb
  chef/cookbooks/provisioner/recipes/update_nodes.rb
Labels: backport from SOC9, bug

#1670 [4.0] provisioner: Skip vxlan virtual devices
  chef/cookbooks/ohai/recipes/default.rb
  chef/cookbooks/provisioner/recipes/update_nodes.rb
Labels: backport from SOC9, bug

#1676 crowbar: move skip unready nodes out of experimental
  crowbar_framework/app/models/service_object.rb
  crowbar_framework/config/application.rb
  crowbar_framework/config/crowbar.yml
  crowbar_framework/config/experimental.yml
Labels: needs backport to SOC7, needs backport to SOC8

#1668 upgrade: Cluster health check was extended with one more check
  crowbar_framework/app/models/api/upgrade.rb
  crowbar_framework/config/locales/crowbar/en.yml
Labels: forward-port from SOC7, upgrade

#1680 [5.0] crowbar: move skip unready nodes out of experimental
  crowbar_framework/app/models/service_object.rb
  crowbar_framework/config/application.rb
  crowbar_framework/config/crowbar.yml
  crowbar_framework/config/experimental.yml
Labels: backport from SOC9

#1681 [4.0] crowbar: move skip unready nodes out of experimental
  crowbar_framework/app/models/service_object.rb
  crowbar_framework/config/application.rb
  crowbar_framework/config/crowbar.yml
  crowbar_framework/config/experimental.yml
Labels: backport from SOC9

#1689 upgrade: Do not start chef-client service from recipe
  chef/cookbooks/crowbar/recipes/crowbar-upgrade.rb
  crowbar_framework/app/models/api/upgrade.rb
Labels: needs forward-port to SOC9, upgrade, wip

#1688 crowbar: move skip unchanged batches out of experimental
  crowbar_framework/app/models/service_object.rb
  crowbar_framework/config/crowbar.yml
  crowbar_framework/config/experimental.yml
Labels: needs backport to SOC7, needs backport to SOC8

#1690 [4.0] crowbar: move skip unchanged batches feature out of experimental
  crowbar_framework/app/models/service_object.rb
  crowbar_framework/config/crowbar.yml
  crowbar_framework/config/experimental.yml
Labels: backport from SOC9

#1691 [5.0] Crowbar: move skip unchanged batches feature out of experimental 5
  crowbar_framework/app/models/service_object.rb
  crowbar_framework/config/crowbar.yml
  crowbar_framework/config/experimental.yml
Labels: backport from SOC9

#1692 upgrade: Do not start chef-client service from recipe
  chef/cookbooks/crowbar/recipes/crowbar-upgrade.rb
  crowbar_framework/app/models/api/upgrade.rb
Labels: forward-port from SOC8, upgrade
