Repository crowbar/crowbar-core, pull requests merged in 2018-02, with the labels that each got.

#1493 [4.0] crowbar_batch: fix host_by_alias
  bin/crowbar_batch
Labels: backport from SOC8

#1490 crowbar_batch: fix host_by_alias
  bin/crowbar_batch
Labels: needs backport to SOC6, needs backport to SOC7

#1494 [3.0] crowbar_batch: fix host_by_alias
  bin/crowbar_batch
Labels: backport from SOC8

#1491 network: restore default route after 'wicked ifup all' (bsc#1075368)
  chef/cookbooks/network/recipes/default.rb
Labels: needs backport to SOC7
