Repository crowbar/crowbar-core, pull requests merged in 2018-04, with the labels that each got.

#1521 [4.0] network: Only set bond attributes when they change (bsc#1054268)
  chef/cookbooks/network/recipes/default.rb
Labels: backport from SOC8

#1522 [3.0] network: Only set bond attributes when they change (bsc#1054268)
  chef/cookbooks/network/recipes/default.rb
Labels: backport from SOC8

#1492 crowbar: skip deleted nodes on updating data bags
  crowbar_framework/app/models/dns_service.rb
  crowbar_framework/app/models/logging_service.rb
  crowbar_framework/app/models/ntp_service.rb
Labels: bug, needs backport to SOC7

#1526 crowbar: use hostname file to validate host name
  crowbar_framework/app/models/api/backup.rb
Labels: needs backport to SOC6, needs backport to SOC7

#1528 [3.0] crowbar: use hostname file to validate host name
  crowbar_framework/app/models/backup.rb
Labels: backport from SOC8

#1527 [4.0] crowbar: use hostname file to validate host name
  crowbar_framework/app/models/api/backup.rb
Labels: backport from SOC8

#1529 [4.0] crowbar: skip deleted nodes on updating data bags
  crowbar_framework/app/models/dns_service.rb
  crowbar_framework/app/models/logging_service.rb
  crowbar_framework/app/models/ntp_service.rb
Labels: backport from SOC8

#1531 upgrade: use proper product name for cloud 8
  crowbar_framework/app/models/api/upgrade.rb
  crowbar_framework/spec/models/api/upgrade_spec.rb
Labels: bug, needs backport to SOC7, upgrade

#1530 service: fix failure on transition to readying
  chef/data_bags/crowbar/template-salt.json
  crowbar_framework/app/models/service_object.rb
Labels: bug, needs backport to SOC7

#1535 Allow sanity controller during upgrade
  crowbar_framework/app/controllers/sanities_controller.rb
Labels: upgrade

#1538 crowbar: Use proper repo for cloud8 Update
  crowbar_framework/config/repos-cloud.yml
Labels: upgrade

#1533 [4.0] upgrade: use proper product name for cloud 8
  crowbar_framework/app/models/api/upgrade.rb
  crowbar_framework/spec/models/api/upgrade_spec.rb
Labels: backport from SOC8, upgrade

#1541 upgrade: fix horizon deprecated config
  chef/cookbooks/crowbar/templates/default/crowbar-upgrade-os.sh.erb
Labels: upgrade

#1532 service: fix failure on transition to readying
  crowbar_framework/app/models/service_object.rb
Labels: backport from SOC8, bug

#1545 [4.0] Expect the logger argument in the constructor (bsc#1089448)
  crowbar_framework/app/models/suse_manager_client_service.rb
  crowbar_framework/app/models/updater_service.rb
Labels: backport from SOC8

#1543 Add common cinder group for all nodes (bsc#1087896)
  chef/cookbooks/provisioner/templates/default/autoyast.xml.erb
  chef/cookbooks/provisioner/templates/suse/crowbar_register.erb
Labels: forward-port from SOC7

#1539 crowbar: test for find_node_by_name_or_alias
  crowbar_framework/spec/models/node_object_spec.rb
Labels: needs backport to SOC7

#1540 [4.0] Crowbar find node by name or alias test backport
  crowbar_framework/spec/models/node_object_spec.rb
Labels: backport from SOC8

#1549 [4.0] upgrade: Fixes for prepare step
  chef/cookbooks/crowbar/recipes/crowbar-upgrade.rb
  crowbar_framework/app/models/crowbar_service.rb
Labels: upgrade

#1546 crowbar: add validator for n nodes or cluster
  crowbar_framework/app/models/service_object.rb
Labels: needs backport to SOC7

#1556 [4.0] crowbar: add validator for multiple nodes or cluster
  crowbar_framework/app/models/service_object.rb
Labels: backport from SOC8

#1560 ohai: fix hound style errors
  chef/cookbooks/ohai/files/default/plugins/linux/block_device_extended.rb
Labels: needs backport to SOC7

#1559 ohai: Treat struct as fixed length instead of zero terminated string
  chef/cookbooks/ohai/files/default/plugins/crowbar.rb
Labels: needs backport to SOC7

#1562 provisioner: Ensure that crowbarctl is installed on nodes
  chef/cookbooks/provisioner/recipes/base.rb
Labels: needs backport to SOC7

#1566 [4.0] provisioner: Ensure that crowbarctl is installed on nodes
  chef/cookbooks/provisioner/recipes/base.rb
Labels: backport from SOC8

#1569 ohai: Treat struct as fixed length instead of zero terminated (bsc#1090370)
  chef/cookbooks/ohai/files/default/plugins/crowbar.rb
Labels: backport from SOC8
