Repository crowbar/crowbar-core, pull requests merged in 2018-03, with the labels that each got.

#1506 crowbar: fix call to gensslcert
  chef/cookbooks/crowbar/recipes/default.rb
Labels: backport from SOC8, bug

#1495 provisioner: Install microcode packages (bsc#1074665)
  chef/cookbooks/provisioner/recipes/update_nodes.rb
  chef/cookbooks/provisioner/templates/default/autoyast.xml.erb
  chef/cookbooks/provisioner/templates/suse/crowbar_register.erb
Labels: needs backport to SOC7

#1499 provisioner: replace curl calls to crowbar API with crowbarctl
  bin/gather_logs.sh
  bin/transition.sh
  chef/cookbooks/crowbar/files/default/crowbar
  chef/cookbooks/provisioner/recipes/setup_base_images.rb
  chef/cookbooks/provisioner/recipes/update_nodes.rb
  chef/cookbooks/provisioner/templates/default/autoyast-upgrade.xml.erb
  chef/cookbooks/provisioner/templates/default/autoyast.xml.erb
  chef/cookbooks/provisioner/templates/default/crowbar_join.suse.sh.erb
  chef/cookbooks/provisioner/templates/suse/crowbar_register.erb
  updates/control_lib.sh
Labels: needs backport to SOC7

#1513 [4.0] provisioner: replace curl calls to crowbar API with crowbarctl
  bin/gather_logs.sh
  bin/transition.sh
  chef/cookbooks/crowbar/files/default/crowbar
  chef/cookbooks/provisioner/recipes/setup_base_images.rb
  chef/cookbooks/provisioner/recipes/update_nodes.rb
  chef/cookbooks/provisioner/templates/default/autoyast-upgrade.xml.erb
  chef/cookbooks/provisioner/templates/default/autoyast.xml.erb
  chef/cookbooks/provisioner/templates/default/crowbar_join.suse.sh.erb
  chef/cookbooks/provisioner/templates/suse/crowbar_register.erb
  updates/control_lib.sh
Labels: backport from SOC8

#1516 ohai: Do not fail when tcpdump output is missing
  chef/cookbooks/ohai/files/default/plugins/crowbar.rb
Labels: needs backport to SOC7
