Repository crowbar/crowbar-core, pull requests merged in 2018-07, with the labels that each got.

#1616 upgrade: Do not allow cinder-volume on compute nodes
  crowbar_framework/app/models/api/crowbar.rb
  crowbar_framework/spec/models/api/crowbar_spec.rb
Labels: forward-port from SOC7, upgrade

#1613 [stable/4.0] upgrade: Check input is a valid node for nodes
  crowbar_framework/app/controllers/api/upgrade_controller.rb
Labels: backport from SOC8, upgrade

#1571 control_lib: fix host allocation check
  updates/control_lib.sh
Labels: needs forward-port to SOC8

#1624 [4.0] upgrade: Do not allow manila-share on compute nodes
  crowbar_framework/app/models/api/crowbar.rb
Labels: upgrade

#1619 upgrade: Reset RabbitMQ nodes during upgrade
  chef/cookbooks/crowbar/recipes/prepare-upgrade-scripts.rb
  chef/cookbooks/crowbar/templates/default/crowbar-delete-pacemaker-resources.sh.erb
Labels: upgrade

#1627 upgrade: Refresh repos before crowbar-ui update (bsc#1099392)
  crowbar_framework/app/models/api/upgrade.rb
Labels: do not merge yet, upgrade

#1626 [4.0] upgrade: Raise the default timeouts for most time consuming actions
  crowbar_framework/lib/crowbar/upgrade_timeouts.rb
Labels: backport from SOC8, upgrade

#1632 Fix exception handling in get_log_lines
  crowbar_framework/app/models/service_object.rb
Labels: needs backport to SOC7

#1633 [4.0] Fix exception handling in get_log_lines
  crowbar_framework/app/models/service_object.rb
Labels: backport from SOC8

#1629 [4.0] apache: copytruncate apache logs bsc#1083093
  chef/cookbooks/apache2/templates/default/apache.logrotate.erb
Labels: backport from SOC8
