Repository crowbar/crowbar-core, pull requests merged in 2018-11, with the labels that each got.

#1685 crowbar: move disallow chef restarts out of experimental
  crowbar_framework/app/controllers/api/restart_management_controller.rb
  crowbar_framework/config/application.rb
  crowbar_framework/config/crowbar.yml
  crowbar_framework/config/experimental.yml
  crowbar_framework/config/locales/crowbar/en.yml
  crowbar_framework/spec/controllers/api/restart_management_controller_spec.rb
Labels: needs backport to SOC7, needs backport to SOC8

#1706 [5.0] upgrade: Add an initial check if there's anything running on a host
  chef/cookbooks/crowbar/templates/default/crowbar-evacuate-host.sh.erb
Labels: upgrade

#1708 [4.0] upgrade: Allow upgrade with monasca agents on compute nodes
  crowbar_framework/app/models/api/crowbar.rb
Labels: needs forward-port to SOC8, needs forward-port to SOC9, upgrade

#1703 [5.0] upgrade: If pacemaker is used to manage the services, don't use systemctl
  chef/cookbooks/crowbar/recipes/prepare-upgrade-scripts.rb
  chef/cookbooks/crowbar/templates/default/crowbar-shutdown-services-before-upgrade.sh.erb
  crowbar_framework/app/models/api/upgrade.rb
  crowbar_framework/app/models/crowbar_service.rb
Labels: upgrade

#1712 crowbar: Do not rewrite the value of 'insecure' if it already exist
  chef/data_bags/crowbar/migrate/crowbar/200_add_insecure_attribute.rb
Labels: forward-port from SOC8

#1710 upgrade: Allow upgrade with monasca agents on compute nodes
  crowbar_framework/app/models/api/crowbar.rb
Labels: forward-port from SOC7, upgrade

#1709 [5.0]upgrade: Allow upgrade with monasca agents on compute nodes
  crowbar_framework/app/models/api/crowbar.rb
Labels: forward-port from SOC7, upgrade

#1714 [4.0] upgrade: Improve handling of zypper prompts (bsc#1116853)
  crowbar_framework/app/models/api/upgrade.rb
  crowbar_framework/config/locales/crowbar/en.yml
  crowbar_framework/spec/fixtures/crowbar_repocheck_zypper_prompt.xml
  crowbar_framework/spec/models/api/upgrade_spec.rb
Labels: upgrade
