Repository crowbar/crowbar-core, pull requests merged in 2018-12, with the labels that each got.

#1722 [5.0] upgrade: Fix condition for setting clone_stateless value
  chef/cookbooks/crowbar/recipes/prepare-upgrade-scripts.rb
Labels: upgrade

#1727 [4.0] provisioner: validate format of additional ssh keys section
  crowbar_framework/app/models/provisioner_service.rb
Labels: backport from SOC9

#1725 [5.0] provisioner: validate format of additional ssh keys section
  crowbar_framework/app/models/provisioner_service.rb
Labels: backport from SOC9

#1733 crowbar: avoid nil crash when provisioner attributes are not set
  crowbar_framework/app/models/node.rb
Labels: needs backport to SOC7, needs backport to SOC8

#1728 conduits: match base_board.serial_number as well
  crowbar_framework/lib/crowbar/conduit_resolver.rb
Labels: needs backport to SOC7, needs backport to SOC8

#1719 [5.0] upgrade: Improve handling of zypper prompts (bsc#1116853)
  crowbar_framework/app/models/api/upgrade.rb
  crowbar_framework/config/locales/crowbar/en.yml
  crowbar_framework/spec/fixtures/crowbar_repocheck_zypper_prompt.xml
  crowbar_framework/spec/models/api/upgrade_spec.rb
Labels: forward-port from SOC7, upgrade

#1718 upgrade: Improve handling of zypper prompts (bsc#1116853)
  crowbar_framework/app/models/api/upgrade.rb
  crowbar_framework/config/locales/crowbar/en.yml
  crowbar_framework/spec/fixtures/crowbar_repocheck_zypper_prompt.xml
  crowbar_framework/spec/models/api/upgrade_spec.rb
Labels: forward-port from SOC7, forward-port from SOC8, upgrade

#1736 upgrade: Revert "upgrade: Deleting cinder services from database no longer needed
  chef/cookbooks/crowbar/recipes/prepare-upgrade-scripts.rb
  chef/cookbooks/crowbar/templates/default/crowbar-delete-cinder-services-before-upgrade.sh.erb
  crowbar_framework/app/models/api/upgrade.rb
Labels: upgrade

#1721 upgrade: Increase delayed_job time limit
  crowbar_framework/config/initializers/delayed_job_config.rb
Labels: needs forward-port to SOC8, needs forward-port to SOC9, upgrade

#1738 upgrade: Increase delayed_job time limit
  crowbar_framework/config/initializers/delayed_job_config.rb
Labels: forward-port from SOC7, upgrade

#1715 [5.0] upgrade: reduce keystone downtime
  chef/cookbooks/apache2/definitions/apache_site.rb
  chef/cookbooks/crowbar/recipes/prepare-upgrade-scripts.rb
  chef/cookbooks/crowbar/templates/default/crowbar-delete-pacemaker-resources.sh.erb
  chef/cookbooks/crowbar/templates/default/crowbar-migrate-keystone-and-start.sh.erb
  chef/cookbooks/crowbar/templates/default/crowbar-shutdown-keystone.sh.erb
  chef/cookbooks/crowbar/templates/default/crowbar-shutdown-remaining-services.sh.erb
  crowbar_framework/app/models/api/upgrade.rb
Labels: needs forward-port to SOC9, upgrade

#1731 [5.0] upgrade: Mark correctly the set of nodes that was selected for upgrade
  crowbar_framework/app/controllers/api/upgrade_controller.rb
Labels: needs forward-port to SOC9, upgrade

#1737 [5.0] upgrade: Increase delayed_job time limit
  crowbar_framework/config/initializers/delayed_job_config.rb
Labels: forward-port from SOC7, upgrade

#1730 upgrade: Introduce parallelism into the upgrade of compute nodes
  crowbar_framework/app/controllers/api/upgrade_controller.rb
  crowbar_framework/app/models/api/node.rb
  crowbar_framework/app/models/api/upgrade.rb
  crowbar_framework/app/models/node.rb
Labels: forward-port from SOC8, upgrade

#1698 Add ping support for IPv6
  crowbar_framework/lib/crowbar/checks/network.rb
  crowbar_framework/spec/lib/crowbar/checks/network_spec.rb
Labels: IPv6-CP

#1744 [5.0] upgrade: Reset the current nodes list before new set of nodes
  crowbar_framework/app/models/api/upgrade.rb
Labels: needs forward-port to SOC9, upgrade

#1704 Ipv6 support in the crowbar_validator
  crowbar_framework/app/models/crowbar_validator.rb
Labels: IPv6-CP

#1716 network: add IPv6 and CIDR support
  chef/cookbooks/network/recipes/default.rb
  crowbar_framework/app/models/network_service.rb
Labels: IPv6-CP
