Repository crowbar/crowbar-core, pull requests merged in 2019-08, with the labels that each got.

#1885 [5.0] travis: Whitelist CVE-2015-3448 (SOC-9911) + Travis Improvements (SOC-9565)
  .travis.yml
  Dangerfile
  Gemfile
Labels: backport from SOC9

#1886 [4.0] travis: Whitelist CVE-2015-3448 (SOC-9911) + Travis Improvements (SOC-9565)
  .travis.yml
Labels: backport from SOC9

#1870 dns: fix migration for designate
  chef/data_bags/crowbar/migrate/dns/301_add_rndckey.rb
Labels: needs backport to SOC8

#1891 ovs-pre-up: remove controller for admin bridge (SOC-10073)
  chef/cookbooks/network/templates/default/ovs-pre-up.sh.erb
Labels: needs backport to SOC7, needs backport to SOC8

#1892 [5.0] ovs-pre-up: remove controller for admin bridge (SOC-10073)
  chef/cookbooks/network/templates/default/ovs-pre-up.sh.erb
Labels: backport from SOC9

#1893 [4.0] ovs-pre-up: remove controller for admin bridge (SOC-10073)
  chef/cookbooks/network/templates/default/ovs-pre-up.sh.erb
Labels: backport from SOC9

#1896 upgrade: remove nova-consoleauth service entries on upgrade (SOC-10164)
  chef/cookbooks/crowbar/templates/default/crowbar-delete-unknown-nova-services.sh.erb
  chef/cookbooks/crowbar/templates/default/crowbar-reload-nova-after-upgrade.sh.erb
Labels: upgrade

#1902 upgrade: restart nova services after upgrade
  chef/cookbooks/crowbar/templates/default/crowbar-reload-nova-after-upgrade.sh.erb
Labels: upgrade

#1903 ohai: Hardcode ruby version for package installation (SOC-10010)
  chef/cookbooks/ohai/recipes/default.rb
Labels: needs backport to SOC7, needs backport to SOC8

#1890 upgrade: Re-run upgrade on non-compute nodes (SOC-10072)
  crowbar_framework/app/models/api/upgrade.rb
  crowbar_framework/spec/models/api/upgrade_spec.rb
Labels: upgrade

#1907 upgrade: Add more prechecks for 8->9 (SOC-9868)
  crowbar_framework/app/models/api/crowbar.rb
  crowbar_framework/app/models/api/upgrade.rb
  crowbar_framework/config/locales/crowbar/en.yml
Labels: upgrade

#1853 network: reduce risk of creating network loops
  chef/cookbooks/barclamp/libraries/nic.rb
  chef/cookbooks/network/recipes/default.rb
Labels: needs backport to SOC7, needs backport to SOC8

#1910 [5.0] Add CVE-2019-5477 the to travis ignore list (SOC-9635)
  .travis.yml
Labels: backport from SOC9

#1911 [4.0] Add CVE-2019-5477 the to travis ignore list (SOC-9635)
  .travis.yml
Labels: backport from SOC9
