Repository crowbar/crowbar-core, pull requests merged in 2019-09, with the labels that each got.

#1898 [5.0] network: reduce risk of creating network loops
  chef/cookbooks/barclamp/libraries/nic.rb
  chef/cookbooks/network/recipes/default.rb
Labels: backport from SOC9

#1915 [5.0] Remove dubious uses of machine-install user
  bin/gather_logs.sh
  bin/transition.sh
  chef/cookbooks/crowbar/files/default/crowbar
Labels: backport from SOC9

#1914 [4.0] Remove dubious uses of machine-install user
  bin/gather_logs.sh
  bin/transition.sh
  chef/cookbooks/crowbar/files/default/crowbar
Labels: backport from SOC9

#1899 [4.0] network: reduce risk of creating network loops
  chef/cookbooks/barclamp/libraries/nic.rb
  chef/cookbooks/network/recipes/default.rb
Labels: backport from SOC9

#1897 [4.0] network: Allow locking down the network config for nodes (bsc#1120657)
  chef/cookbooks/network/recipes/role_network.rb
Labels: backport from SOC9

#1883 upgrade: dump Monasca, Grafana databases (SOC-9772)
  chef/cookbooks/crowbar/recipes/prepare-upgrade-scripts.rb
  chef/cookbooks/crowbar/templates/default/crowbar-dump-monasca-db.sh.erb
  chef/cookbooks/crowbar/templates/default/crowbar-shutdown-services-before-upgrade.sh.erb
  crowbar_framework/app/models/api/upgrade.rb
Labels: upgrade

#1916 upgrade: Upgrade compute services early (SOC-10273)
  chef/cookbooks/crowbar/templates/default/crowbar-pre-upgrade.sh.erb
  chef/cookbooks/crowbar/templates/default/crowbar-reload-nova-after-upgrade.sh.erb
  crowbar_framework/app/models/api/upgrade.rb
Labels: upgrade

#1923 upgrade: Fix pre-checks tests (SOC-9868)
  crowbar_framework/spec/models/api/crowbar_spec.rb
Labels: upgrade

#1926 upgrade: Fix pie chart colors on dashboard (SOC-10619)
  crowbar_framework/app/assets/javascripts/application.js
  crowbar_framework/vendor/assets/javascripts/jquery/ledUpdate.js
Labels: needs backport to SOC8, upgrade

#1927 [5.0] upgrade: Fix pie chart colors on dashboard (SOC-10619)
  crowbar_framework/app/assets/javascripts/application.js
  crowbar_framework/vendor/assets/javascripts/jquery/ledUpdate.js
Labels: backport from SOC9, upgrade
