Repository crowbar/crowbar-core, pull requests merged in 2019-07, with the labels that each got.

#1865 [5.0] crowbar: Save sync_mark attributes in databag
  chef/data_bags/crowbar/migrate/crowbar/201_add_sync_mark.rb
  chef/data_bags/crowbar/template-crowbar.json
  chef/data_bags/crowbar/template-crowbar.schema
  crowbar_framework/app/models/crowbar_service.rb
  crowbar_framework/spec/fixtures/data_bags/template-crowbar.json
Labels: backport from SOC9

#1875 network: Don't set datapath-ids on ovs-bridges anymore
  chef/cookbooks/barclamp/libraries/nic.rb
  chef/cookbooks/network/recipes/default.rb
  chef/cookbooks/network/templates/default/ovs-pre-up.sh.erb
Labels: backport from SOC9

#1866 [4.0] crowbar: Save sync_mark attributes in databag
  chef/data_bags/crowbar/migrate/crowbar/105_add_sync_mark.rb
  chef/data_bags/crowbar/template-crowbar.json
  chef/data_bags/crowbar/template-crowbar.schema
  crowbar_framework/app/models/crowbar_service.rb
  crowbar_framework/spec/fixtures/data_bags/template-crowbar.json
Labels: backport from SOC9

#1874 upgrade: update file names for 8 -> 9 (SOC-9029)
  crowbar_framework/app/models/api/upgrade.rb
  crowbar_framework/spec/controllers/machines_controller_spec.rb
  crowbar_framework/spec/models/api/upgrade_spec.rb
Labels: upgrade

#1860 [4.0] deployer: Use dhcp on crowbar_register only when enable_pxe is set (bsc#1132654)
  chef/cookbooks/provisioner/recipes/setup_base_images.rb
  chef/cookbooks/provisioner/templates/suse/crowbar_register.erb
Labels: backport from SOC8

#1881 Cleanup clone_stateless_services leftovers (SOC-9842)
  chef/cookbooks/crowbar/templates/default/crowbar-pre-upgrade.sh.erb
  chef/cookbooks/crowbar/templates/default/crowbar-shutdown-remaining-services.sh.erb
  chef/cookbooks/crowbar/templates/default/crowbar-shutdown-services-before-upgrade.sh.erb
  crowbar_framework/app/models/api/upgrade.rb
  crowbar_framework/app/models/crowbar_service.rb
Labels: upgrade

#1871 [5.0] dns: fix migration for designate
  chef/data_bags/crowbar/migrate/dns/103_add_rndckey.rb
Labels: backport from SOC9

#1876 monasca: remove Java persister (SOC-9482)
  chef/cookbooks/crowbar/recipes/prepare-upgrade-scripts.rb
  chef/cookbooks/crowbar/templates/default/crowbar-monasca-cleanups.sh.erb
  crowbar_framework/app/models/api/upgrade.rb
Labels: upgrade

#1882 batch: Format crowbar batch error output
  bin/crowbar_batch
Labels: needs backport to SOC7, needs backport to SOC8
