Repository crowbar/crowbar-core, pull requests merged in 2019-06, with the labels that each got.

#1854 network: Allow locking down the network config for nodes (bsc#1120657)
  chef/cookbooks/network/recipes/role_network.rb
Labels: needs backport to SOC7, needs backport to SOC8

#1862 Allow restricted API access during upgrade
  crowbar_framework/app/controllers/restricted_controller.rb
Labels: upgrade

#1863 crowbar: Save sync_mark attributes in databag
  chef/data_bags/crowbar/migrate/crowbar/303_add_sync_mark.rb
  chef/data_bags/crowbar/template-crowbar.json
  chef/data_bags/crowbar/template-crowbar.schema
  crowbar_framework/app/models/crowbar_service.rb
  crowbar_framework/spec/fixtures/data_bags/template-crowbar.json
Labels: needs backport to SOC7, needs backport to SOC8

#1857 dns: fix designate migration
  chef/data_bags/crowbar/migrate/dns/301_add_rndckey.rb
Labels: upgrade

#1856 [5.0 ]Stable 5.0 bsc1120657
  chef/cookbooks/network/recipes/role_network.rb
Labels: backport from SOC9

#1859 [5.0] deployer: Use dhcp on crowbar_register only when enable_pxe is set (bsc#1132654)
  chef/cookbooks/provisioner/recipes/setup_base_images.rb
  chef/cookbooks/provisioner/templates/suse/crowbar_register.erb
Labels: backport from SOC9

#1847 network: Don't set datapath-ids on ovs-bridges anymore
  chef/cookbooks/barclamp/libraries/nic.rb
  chef/cookbooks/network/recipes/default.rb
  chef/cookbooks/network/templates/default/ovs-pre-up.sh.erb
Labels: needs backport to SOC8

#1867 [5.0] travis: pin sexp_processor to 4.12.0
  crowbar_framework/Gemfile
Labels: backport from SOC9

#1868 [4.0] travis: pin sexp_processor to 4.12.0
  crowbar_framework/Gemfile
Labels: backport from SOC9

#1745 upgrade: Mark correctly the set of nodes that was selected for upgrade
  crowbar_framework/app/controllers/api/upgrade_controller.rb
Labels: forward-port from SOC8, upgrade
