Repository crowbar/crowbar-core, pull requests merged in 2019-05, with the labels that each got.

#1816 Fix order of values in nodes piechart
  crowbar_framework/vendor/assets/javascripts/jquery/ledUpdate.js
Labels: needs backport to SOC7, needs backport to SOC8

#1849 [5.0] Ignore CVE-2019-11068 during Travis (SOC-9262)
  .travis.yml
Labels: backport from SOC9

#1850 [4.0] Ignore CVE-2019-11068 during Travis (SOC-9262)
  .travis.yml
Labels: backport from SOC9

#1844 [5.0] Fix order of values in nodes piechart
  crowbar_framework/vendor/assets/javascripts/jquery/ledUpdate.js
Labels: backport from SOC9

#1843 [4.0] Fix order of values in nodes piechart
  crowbar_framework/vendor/assets/javascripts/jquery/ledUpdate.js
Labels: backport from SOC9

#1840 provisioner: enabled tuned profiles
  chef/cookbooks/provisioner/recipes/base.rb
Labels: do not merge yet

#1845 [5.0] barclamp: Fix setting MTU on networks using a bridge
  chef/cookbooks/barclamp/libraries/nic.rb
Labels: backport from SOC9

#1846 [4.0] barclamp: Fix setting MTU on networks using a bridge
  chef/cookbooks/barclamp/libraries/nic.rb
Labels: backport from SOC9
