Repository crowbar/crowbar-core, pull requests merged in 2019-02, with the labels that each got.

#1787 [5.0] upgrade: Block access to crowbar UI for both upgrade paths
  crowbar_framework/app/controllers/application_controller.rb
Labels: upgrade

#1788 [5.0] upgrade: Update the repository names required for SOC9
  crowbar_framework/app/models/api/upgrade.rb
  crowbar_framework/spec/fixtures/crowbar_repocheck.json
  crowbar_framework/spec/models/api/upgrade_spec.rb
Labels: upgrade

#1789 [5.0] upgrade: Check for the correct file indicating postponed upgrade
  crowbar_framework/lib/crowbar/upgrade_status.rb
Labels: needs forward-port to SOC9, upgrade

#1767 [4.0] apache2: enable sslsessioncache
  chef/cookbooks/apache2/templates/suse/mods/ssl.conf.erb
Labels: backport from SOC8, backport from SOC9

#1766 [5.0] apache2: enable sslsessioncache
  chef/cookbooks/apache2/templates/suse/mods/ssl.conf.erb
Labels: backport from SOC9

#1786 provisioner: Remove references to windows admin password (bsc#1123640)
  crowbar_framework/app/views/barclamp/provisioner/_edit_attributes.html.haml
  crowbar_framework/config/locales/provisioner/en.yml
Labels: needs backport to SOC8

#1773 upgrade: Adapt crowbar to handle 8-9 upgrade correctly
  crowbar_framework/app/controllers/api/upgrade_controller.rb
  crowbar_framework/app/controllers/application_controller.rb
  crowbar_framework/config/initializers/end_adminupgrade.rb
  crowbar_framework/lib/crowbar/upgrade_status.rb
  crowbar_framework/spec/controllers/api/upgrade_controller_spec.rb
Labels: upgrade

#1792 [5.0] Support RAID 0
  crowbar_framework/app/controllers/nodes_controller.rb
  crowbar_framework/app/helpers/form_helper.rb
  crowbar_framework/config/locales/crowbar/en.yml
Labels: backport from SOC9

#1791 [4.0] Support RAID 0
  crowbar_framework/app/controllers/nodes_controller.rb
  crowbar_framework/app/helpers/form_helper.rb
  crowbar_framework/config/locales/crowbar/en.yml
Labels: backport from SOC9

#1790 [5.0] upgrade: Delay status switch after upgrade ends
  crowbar_framework/lib/crowbar/upgrade_status.rb
  crowbar_framework/spec/lib/crowbar/upgrade_status_spec.rb
Labels: upgrade

#1793 upgrade: Create update repositories with refresh enabled
  chef/cookbooks/crowbar/templates/default/crowbar-prepare-repositories.sh.erb
Labels: needs backport to SOC8, upgrade

#1794 [5.0] upgrade: Create update repositories with refresh enabled
  chef/cookbooks/crowbar/templates/default/crowbar-prepare-repositories.sh.erb
Labels: backport from SOC9, upgrade

#1441 network: run ifdown for vlan interface cleanup
  chef/cookbooks/network/recipes/default.rb
Labels: needs backport to SOC7

#1795 [4.0] upgrade: Delay status switch after upgrade ends
  crowbar_framework/lib/crowbar/upgrade_status.rb
  crowbar_framework/spec/lib/crowbar/upgrade_status_spec.rb
Labels: backport from SOC8

#1798 network: run wicked ifdown for interface cleanup (bsc#1063535)
  chef/cookbooks/network/recipes/default.rb
Labels: backport from SOC9
