Repository crowbar/crowbar-core, pull requests merged in 2019-10, with the labels that each got.

#1936 Revert "[upgrade] Use block-migration when needed"
  chef/cookbooks/crowbar/recipes/prepare-upgrade-scripts.rb
  chef/cookbooks/crowbar/templates/default/crowbar-evacuate-host.sh.erb
Labels: needs backport to SOC8

#1941 Revert "Use block-migration when needed" (SOC-10133)
  chef/cookbooks/crowbar/recipes/prepare-upgrade-scripts.rb
  chef/cookbooks/crowbar/templates/default/crowbar-evacuate-host.sh.erb
Labels: backport from SOC9

#1872 crowbar: Give more time for reboot for physical hardware reboots
  crowbar_framework/app/models/api/node.rb
Labels: needs backport to SOC8

#1943 upgrade: Reload repo config in repochecks (SOC-10718)
  crowbar_framework/app/models/api/node.rb
Labels: upgrade
