Repository crowbar/crowbar-core, pull requests merged in 2020-01, with the labels that each got.

#1989 [5.0] crowbar: avoid nil crash when provisioner attributes are not set
  crowbar_framework/app/models/node.rb
Labels: backport from SOC9

#1990 [4.0] Avoid nil crash when provisioner attributes are not set (bsc#1160048)
  crowbar_framework/app/models/node.rb
Labels: backport from SOC8

#1986 apache2: Restart after enabling SSL flag (SOC-11029)
  chef/cookbooks/apache2/recipes/mod_ssl.rb
Labels: needs backport to SOC8

#1979 crowbar: add crowbar-pacemaker dependency (SOC-10986)
  chef/cookbooks/crowbar/metadata.json
Labels: needs backport to SOC7, needs backport to SOC8

#1993 [5.0] apache2: Restart after enabling SSL flag (SOC-11029)
  chef/cookbooks/apache2/recipes/mod_ssl.rb
Labels: backport from SOC9

#1988 Upgrade neutron agent together with nova-compute package (SOC-11031)
  chef/cookbooks/crowbar/templates/default/crowbar-pre-upgrade.sh.erb
Labels: upgrade

#1996 [5.0] Do not log an error for a case that is correct (trivial)
  crowbar_framework/app/models/network_service.rb
Labels: backport from SOC9

#1999 [5.0] Show upgrade menu item in SOC8
  crowbar.yml
  crowbar_framework/config/locales/crowbar/en.yml
  crowbar_framework/config/navigation.rb
Labels: forward-port from SOC7, upgrade

#2002 [5.0] network: start OVS before wickedd (SOC-11067)
  chef/cookbooks/network/recipes/default.rb
  chef/cookbooks/network/templates/default/openvswitch.service-wickedd.conf.erb
Labels: backport from SOC9

#2001 [4.0] network: start OVS before wickedd (SOC-11067)
  chef/cookbooks/network/recipes/default.rb
  chef/cookbooks/network/templates/default/openvswitch.service-wickedd.conf.erb
Labels: backport from SOC9
